version: '3'
services:
    app:
        container_name: my-portfolio
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - /media/ehsan/development/samples/portfolio:/app
            - /app/node_modules
        ports:
            - 3000:3000
        environment:
            - CHOKIDAR_USEPOLLING=true
